### ISSUE TITLE
Error on the Node.js example

### ISSUE THREAD

**Issue by rafaelrinaldi** [azukiapp/azkfile-init-examples#9]
I was just trying to demonstrate Azk to a friend by running the Node.js example present on this repository (`node010`). I've performed all the steps described on the 1st scenario but didn't get it running properly.
Here's the full log:

``` sh
λ azk start
? The agent is not running, would you like to start it now? Yes
azk: Wait, this process may take several minutes
azk: Loading settings and checking dependencies.
azk: Checking version...
azk: Settings loaded successfully.
azk: Removing virtual machine...
azk: Virtual machine has been successfully removed.
azk: Agent is being started...
azk: Installing virtual machine...
azk: Virtual machine has been successfully installed.
azk: Starting virtual machine...
azk: Virtual machine has been successfully started.
azk: Waiting for initialization of virtual machine...
azk: Trying connect to vm (tcp://192.168.50.4:2376) (1/10)...
azk: Trying connect to vm (tcp://192.168.50.4:2376) (2/10)...
azk: Trying connect to vm (tcp://192.168.50.4:2376) (3/10)...
azk: Trying connect to vm (tcp://192.168.50.4:2376) (4/10)...
azk: Virtual machine is ready to use.
azk: Upload the ssh key to vm...
azk: Downloading required keys to connect with docker
azk: starting unsfd...
azk: unsfd started in 11003 port with file config: /Users/rafael.rinaldi/.azk/data/run/exports.
azk: mounting the unsfd shared folder in virtual machine...
azk: unsfd shared folder has been successfully mounted.
azk: Trying connect to docker (https://192.168.50.4:2376) (1/5)...
azk: Starting azk dns service...
azk: Dns service started.
azk: Trying connect to docker (https://192.168.50.4:2376) (1/5)...
azk: Starting azk balancer redirect service...
azk: Check if balancer redirect service is up (tcp://192.168.50.4:80) (1/10)...
azk: Balancer redirect started.
azk: Starting memcached service...
azk: Memcached service started.
azk: Starting http balancer service...
azk: Http balancer service started.
azk: Agent has been successfully started.
azk: ↑ starting `node-example` system, 2 new instances...
azk: ✓ checking `node:0.10` image...
azk: ◴ waiting start `node-example` system, try connect port http/tcp...
azk: Run system `node-example` return: (1), for command: /bin/bash -c npm start:
azk: npm ERR! Linux 3.16.7-tinycore64
azk: npm ERR! argv "node" "/usr/local/bin/npm" "start"
azk: npm ERR! node v0.10.35
azk: npm ERR! npm  v2.1.16

azk: npm ERR! missing script: start
azk: npm ERR!
azk: npm ERR! If you need help, you may report this error at:
azk: npm ERR!     <http://github.com/npm/npm/issues>

azk: npm ERR! Please include the following file with any support request:
azk: npm ERR!     /azk/node-example/npm-debug.log

azk: Due to the above error azk will stop all instances already begun.

azk: System `node-example` not running

┌───┬──────────────┬────────────┬──────────────────────┬─────────────────┬───────────────┐
│   │ System       │ Instancies │ Hostname             │ Instances-Ports │ Provisioned   │
├───┼──────────────┼────────────┼──────────────────────┼─────────────────┼───────────────┤
│ ↓ │ node-example │ 0          │ node-example.azk.dev │ -               │ 3 minutes ago │
└───┴──────────────┴────────────┴──────────────────────┴─────────────────┴───────────────┘
```

Here's the `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.1.16
3 info using node@v0.10.35
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:130:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:81:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:51:40
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:17)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
4 verbose stack     at evalmachine.<anonymous>:272:14
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
4 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
5 verbose cwd /azk/node-example
6 error Linux 3.16.7-tinycore64
7 error argv "node" "/usr/local/bin/npm" "start"
8 error node v0.10.35
9 error npm  v2.1.16
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by saitodisse** [comment]
Hi @rafaelrinaldi! 
It seems that the problem is simple. What happens is that by default `Azkfile.js` runs "npm start":
```js
     command: "npm start"
```

and on `package.json`:
```js
"scripts": {
  "start": "node app.js"
},
```

You must create a file named `app.js`, or change the `Azkfile.js` and the `package.json`.
I hope this helps

**Comment by rafaelrinaldi** [comment]
Thanks @saitodisse! The problem is that I've cloned a different repository (the one specified on the README file points to `auzukiapp-samples/node-example`). I've made the change: https://github.com/azukiapp-samples/node-example/pull/2

**Comment by WendyMcF** [comment]
Thank you, this helped me.

**Comment by MalikOvaiz** [comment]
Can you explain about "app.js" .what that file will contain and where it should be placed?
Thanks

**Comment by gullitmiranda** [comment]
@MalikOvaiz,
In the case presented above, the `app.js` is at the root of the project and contains application startup.
eg: https://github.com/azukiapp/azkfile-init-examples/blob/master/node012/app.js

**Comment by ghost** [comment]
@ saitodisse I have followed your steps,but no luck.

>  ![image](https://cloud.githubusercontent.com/assets/16608680/16232713/f3acf466-37cb-11e6-9fda-ea09b30398b7.png)

**Comment by gullitmiranda** [comment]
@Pavnii could you put here the complete output of what you ran (including the command)? by that I was able to understand was to just run `node app.js`.

**Comment by ghost** [comment]
I validated my package.json,had some issues,fixed that.
I changed directory to my project and gave npm start ,now I get following:

> ![image](https://cloud.githubusercontent.com/assets/16608680/16257631/f4177ac8-3859-11e6-9a0d-77a066a40a6f.png)
